version: '3.8'

services:
  # 前端服务
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - comic-network

  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - ENV_FILE=.env.production
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URI=mongodb://mongo:27017/comic_db
    volumes:
      - comic-data:/data/downloads
    depends_on:
      - mongo
    networks:
      - comic-network

  # MongoDB数据库
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - comic-network

  # Nginx网关
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - comic-data:/data/downloads
    depends_on:
      - frontend
      - backend
    networks:
      - comic-network

networks:
  comic-network:
    driver: bridge

volumes:
  mongo-data:
  comic-data: 