version: '3.8'

services:
  # 前端服务
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app  # 挂载整个项目目录
      - /app/node_modules  # 排除 node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:3000/api
    command: npm run dev
    networks:
      - comic-network

  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - ENV_FILE=.env.development
      - MONGO_URI=mongodb://mongo:27017/comic_db
    volumes:
      - ./backend:/app  # 挂载源代码目录，实现热重载
      - ./downloads:/data/downloads  # 将下载目录映射到本地的 downloads 文件夹
    depends_on:
      - mongo
    command: uvicorn app.main:app --host 0.0.0.0 --port 3000 --reload  # 开发模式启用热重载
    networks:
      - comic-network

  # MongoDB数据库
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - comic-network

  # MongoDB管理界面（可选）
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongo
    networks:
      - comic-network

networks:
  comic-network:
    driver: bridge

volumes:
  mongo-data:
  comic-data: 